services:
  - type: web
    name: https://app-passwords-laravel.onrender.com
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_STORAGE_LINK
        value: "true"
      - key: DB_HOST
        fromDatabase:
          name: dpg-cvcdqf1c1ekc73eq3vog-a
          property: host
      - key: DB_PORT
        fromDatabase:
          name: 5432
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: app_password
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: app_password_user
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: XlB1xbUMyFXNQ5KMIGQMmrQS9zT3Ak0K
          property: password
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan cache:clear
      php artisan view:clear
      php artisan route:clear
      php artisan migrate --force
      php artisan storage:link
    startCommand: "exit 0"
databases:
  - name: app_password
    databaseName: app_password
    type: postgres # o mysql, dependiendo de tu base de datos